//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2DMServer.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sgoliver.net/", ConfigurationName="ServiceReference1.ServicioRegistroC2DMSoap")]
    public interface ServicioRegistroC2DMSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://sgoliver.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sgoliver.net/RegistroCliente", ReplyAction="*")]
        C2DMServer.ServiceReference1.RegistroClienteResponse RegistroCliente(C2DMServer.ServiceReference1.RegistroClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroCliente", Namespace="http://sgoliver.net/", Order=0)]
        public C2DMServer.ServiceReference1.RegistroClienteRequestBody Body;
        
        public RegistroClienteRequest() {
        }
        
        public RegistroClienteRequest(C2DMServer.ServiceReference1.RegistroClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sgoliver.net/")]
    public partial class RegistroClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string regC2DM;
        
        public RegistroClienteRequestBody() {
        }
        
        public RegistroClienteRequestBody(string usuario, string regC2DM) {
            this.usuario = usuario;
            this.regC2DM = regC2DM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroClienteResponse", Namespace="http://sgoliver.net/", Order=0)]
        public C2DMServer.ServiceReference1.RegistroClienteResponseBody Body;
        
        public RegistroClienteResponse() {
        }
        
        public RegistroClienteResponse(C2DMServer.ServiceReference1.RegistroClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sgoliver.net/")]
    public partial class RegistroClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegistroClienteResult;
        
        public RegistroClienteResponseBody() {
        }
        
        public RegistroClienteResponseBody(int RegistroClienteResult) {
            this.RegistroClienteResult = RegistroClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioRegistroC2DMSoapChannel : C2DMServer.ServiceReference1.ServicioRegistroC2DMSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioRegistroC2DMSoapClient : System.ServiceModel.ClientBase<C2DMServer.ServiceReference1.ServicioRegistroC2DMSoap>, C2DMServer.ServiceReference1.ServicioRegistroC2DMSoap {
        
        public ServicioRegistroC2DMSoapClient() {
        }
        
        public ServicioRegistroC2DMSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioRegistroC2DMSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistroC2DMSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioRegistroC2DMSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        C2DMServer.ServiceReference1.RegistroClienteResponse C2DMServer.ServiceReference1.ServicioRegistroC2DMSoap.RegistroCliente(C2DMServer.ServiceReference1.RegistroClienteRequest request) {
            return base.Channel.RegistroCliente(request);
        }
        
        public int RegistroCliente(string usuario, string regC2DM) {
            C2DMServer.ServiceReference1.RegistroClienteRequest inValue = new C2DMServer.ServiceReference1.RegistroClienteRequest();
            inValue.Body = new C2DMServer.ServiceReference1.RegistroClienteRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.regC2DM = regC2DM;
            C2DMServer.ServiceReference1.RegistroClienteResponse retVal = ((C2DMServer.ServiceReference1.ServicioRegistroC2DMSoap)(this)).RegistroCliente(inValue);
            return retVal.Body.RegistroClienteResult;
        }
    }
}
